---
abstract: 'distribution builder; installer not included!'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires:
  File::Find: 0
  Software::License::None: 0
  Test::Fatal: 0
  Test::File::ShareDir: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla
no_index:
  directory:
    - corpus
    - misc
recommends:
  Term::ReadLine::Gnu: 0
requires:
  App::Cmd::Setup: 0.309
  App::Cmd::Tester: 0.306
  App::Cmd::Tester::CaptureExternal: 0
  Archive::Tar: 0
  CPAN::Meta::Converter: 2.101550
  CPAN::Meta::Prereqs: 2.120630
  CPAN::Meta::Requirements: 2.121
  CPAN::Meta::Validator: 2.101550
  CPAN::Uploader: 0.101550
  Carp: 0
  Class::Load: 0.17
  Config::INI::Reader: 0
  Config::MVP::Assembler: 0
  Config::MVP::Assembler::WithBundles: 0
  Config::MVP::Reader: 2.101540
  Config::MVP::Reader::Findable::ByExtension: 0
  Config::MVP::Reader::Finder: 0
  Config::MVP::Reader::INI: 2
  Config::MVP::Section: 2.200002
  Data::Dumper: 0
  Data::Section: 0.004
  DateTime: 0.44
  Digest::MD5: 0
  Encode: 0
  ExtUtils::MakeMaker: 0
  ExtUtils::Manifest: 1.54
  File::Copy::Recursive: 0
  File::Find::Rule: 0
  File::HomeDir: 0
  File::Path: 0
  File::ShareDir: 0
  File::ShareDir::Install: 0.03
  File::Spec: 0
  File::Temp: 0
  File::pushd: 0
  Hash::Merge::Simple: 0
  JSON: 2
  List::AllUtils: 0
  List::MoreUtils: 0
  List::Util: 0
  Log::Dispatchouli: 1.102220
  Moose: 0.92
  Moose::Autobox: 0.10
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::LazyRequire: 0
  MooseX::Role::Parameterized: 0
  MooseX::SetOnce: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Perl: 0
  PPI: 0
  Params::Util: 0
  Path::Class: 0
  Perl::PrereqScanner: 1.005
  Perl::Version: 0
  Pod::Eventual: 0.091480
  Scalar::Util: 0
  Software::License: 0.101370
  Software::LicenseUtils: 0
  String::Formatter: 0.100680
  String::RewritePrefix: 0.005
  Sub::Exporter: 0
  Sub::Exporter::ForMethods: 0
  Sub::Exporter::Util: 0
  Term::ReadKey: 0
  Term::ReadLine: 0
  Term::UI: 0
  Test::Deep: 0
  Text::Glob: 0.08
  Text::Template: 0
  Try::Tiny: 0
  YAML::Tiny: 0
  autobox: 2.53
  autodie: 0
  base: 0
  namespace::autoclean: 0
  parent: 0
  perl: v5.8.5
  strict: 0
  version: 0
  warnings: 0
resources:
  X_mailing_list: http://www.listbox.com/subscribe/?list_id=139292
  homepage: http://dzil.org/
  repository: http://github.com/rjbs/dist-zilla.git
version: 4.300029
x_Dist_Zilla:
  perl:
    version: 5.017007
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Filter/Git::GatherDir'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Filter/CheckPrereqsIndexed'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Filter/CheckExtraTests'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/@Filter/PruneCruft'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/@Filter/ManifestSkip'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/@Filter/MetaYAML'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/@Filter/License'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/@Filter/Readme'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/@Filter/ExecDir'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/@Filter/ShareDir'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/@Filter/MakeMaker'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/@Filter/Manifest'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/@Filter/TestRelease'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/@Filter/ConfirmRelease'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/@Filter/UploadToCPAN'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: '@Filter/Test::ChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/ReportVersions::Tiny'
      version: 1.08
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Filter/TestMoreWithSubtests'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Filter/GithubMeta'
      version: 0.28
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 2.005
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::ModuleShareDirs
      name: ModuleShareDirs
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: RuntimeRecommends
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::RemovePrereqs
      config:
        Dist::Zilla::Plugin::RemovePrereqs:
          modules_to_remove:
            - Config
            - Dist::Zilla::Tester::_Role
            - Some::Package::That::Does::Not::Exist::Due::To::A::Typo
      name: RemovePrereqs
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: CPANFile
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300029
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300029
