---
abstract: 'distribution builder; installer not included!'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires:
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.31
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101581, CPAN::Meta::Converter version 2.101550'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla
no_index:
  directory:
    - corpus
    - misc
requires:
  App::Cmd::Setup: 0.307
  App::Cmd::Tester: 0.306
  Archive::Tar: 0
  CPAN::Meta::Converter: 2.101550
  CPAN::Meta::Prereqs: 2.101390
  CPAN::Meta::Validator: 2.101550
  CPAN::Uploader: 0.101550
  Carp: 0
  Config: 0
  Config::MVP: 2
  Config::MVP::Assembler: 0
  Config::MVP::Assembler::WithBundles: 0
  Config::MVP::Reader: 2.101540
  Config::MVP::Reader::Findable::ByExtension: 0
  Config::MVP::Reader::Finder: 0
  Config::MVP::Reader::INI: 2
  Config::MVP::Section: 0
  Data::Dumper: 0
  Data::Section: 0.004
  DateTime: 0.44
  ExtUtils::MakeMaker: 0
  ExtUtils::Manifest: 1.54
  File::Copy::Recursive: 0
  File::Find::Rule: 0
  File::HomeDir: 0
  File::Path: 0
  File::ShareDir: 0
  File::ShareDir::Install: 0.03
  File::Spec: 0
  File::Temp: 0
  File::pushd: 0
  Hash::Merge::Simple: 0
  JSON: 2
  List::MoreUtils: 0
  List::Util: 0
  Log::Dispatchouli: 1.100712
  Moose: 0.92
  Moose::Autobox: 0.09
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::LazyRequire: 0
  MooseX::Role::Parameterized: 0
  MooseX::SetOnce: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Perl: 0
  PPI: 0
  Params::Util: 0
  Path::Class: 0
  Perl::PrereqScanner: 0.100830
  Perl::Version: 0
  Pod::Eventual: 0.091480
  Scalar::Util: 0
  Software::License: 0.101370
  Software::LicenseUtils: 0
  String::Formatter: 0.100680
  String::RewritePrefix: 0.005
  Sub::Exporter: 0
  Sub::Exporter::Util: 0
  Text::Template: 0
  Try::Tiny: 0
  Version::Requirements: 0.100630
  YAML::Tiny: 0
  autobox: 2.53
  autodie: 0
  namespace::autoclean: 0
  perl: v5.8.5
  version: 0
resources:
  X_mailing_list: http://www.listbox.com/subscribe/?list_id=139292
  homepage: http://dzil.org/
  repository: http://github.com/rjbs/dist-zilla.git
version: 4.101581
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@RJBS/@Basic/GatherDir'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RJBS/@Basic/PruneCruft'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@RJBS/@Basic/ManifestSkip'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RJBS/@Basic/MetaYAML'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::License
      name: '@RJBS/@Basic/License'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@RJBS/@Basic/Readme'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@RJBS/@Basic/ExtraTests'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RJBS/@Basic/ExecDir'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RJBS/@Basic/ShareDir'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RJBS/@Basic/MakeMaker'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RJBS/@Basic/Manifest'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RJBS/@Basic/TestRelease'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RJBS/@Basic/ConfirmRelease'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RJBS/@Basic/UploadToCPAN'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@RJBS/AutoPrereq'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@RJBS/AutoVersion'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@RJBS/PkgVersion'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RJBS/MetaConfig'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RJBS/MetaJSON'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RJBS/NextRelease'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RJBS/PodSyntaxTests'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@RJBS/Repository'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@RJBS/PodWeaver'
      version: 3.101530
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RJBS/@Git/Check'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RJBS/@Git/Commit'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RJBS/@Git/Tag'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RJBS/@Git/Push'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 1.101550
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereq:
          phase: test
          type: requires
      name: TestRequires
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereq:
          phase: runtime
          type: requires
      name: Prereq
      version: 4.101570
    -
      class: inc::Dist::Zilla::Plugin::VersionBootstrap
      name: VersionBootstrap
      version: 4.101581
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101570
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101570
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 4.101581
