---
abstract: 'distribution builder; installer not included!'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
generated_by: 'Dist::Zilla version 1.093371'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla
requires:
  App::Cmd: 0.299
  Archive::Tar: 0
  CPAN::Uploader: 0
  Config::INI::MVP::Reader: 0.024
  Config::MVP: 0.092990
  Data::Section: 0.004
  DateTime: 0.44
  ExtUtils::MakeMaker: 0
  ExtUtils::Manifest: 1.54
  File::Find::Rule: 0
  File::HomeDir: 0
  File::Temp: 0
  File::chdir: 0
  Hash::Merge::Simple: 0
  List::MoreUtils: 0
  Mixin::ExtraFields::Param: 0
  Moose: 0.92
  Moose::Autobox: 0.09
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Perl::Version: 0
  Pod::Eventual: 0.091480
  Software::License: 0
  String::Flogger: 1
  String::Formatter: 0
  String::RewritePrefix: 0.002
  Test::More: 0
  Text::Template: 0
  YAML::Tiny: 0
  autobox: 2.53
  namespace::autoclean: 0
resources:
  MailingList: http://www.listbox.com/subscribe/?list_id=139292
  homepage: http://search.cpan.org/dist/Dist-Zilla/
  repository: http://github.com/rjbs/dist-zilla
version: 1.093371
