---
abstract: 'distribution builder; installer not included!'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires:
  Software::License::None: 0
  Test::FailWarnings: 0
  Test::Fatal: 0
  Test::File::ShareDir: 0
  Test::More: 0.96
  lib: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.007, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla
no_index:
  directory:
    - corpus
    - misc
recommends:
  Archive::Tar::Wrapper: 0.15
  Term::ReadLine::Gnu: 0
requires:
  App::Cmd::Command::version: 0
  App::Cmd::Setup: 0.309
  App::Cmd::Tester: 0.306
  App::Cmd::Tester::CaptureExternal: 0
  Archive::Tar: 0
  CPAN::Meta::Converter: 2.101550
  CPAN::Meta::Prereqs: 2.120630
  CPAN::Meta::Requirements: 2.121
  CPAN::Meta::Validator: 2.101550
  CPAN::Uploader: 0.103004
  Carp: 0
  Class::Load: 0.17
  Config::INI::Reader: 0
  Config::MVP::Assembler: 0
  Config::MVP::Assembler::WithBundles: 0
  Config::MVP::Reader: 2.101540
  Config::MVP::Reader::Findable::ByExtension: 0
  Config::MVP::Reader::Finder: 0
  Config::MVP::Reader::INI: 2
  Config::MVP::Section: 2.200002
  Data::Dumper: 0
  Data::Section: 0.200002
  DateTime: 0.44
  Digest::MD5: 0
  Encode: 0
  ExtUtils::Manifest: 1.54
  File::Copy::Recursive: 0
  File::Find::Rule: 0
  File::HomeDir: 0
  File::Path: 0
  File::ShareDir: 0
  File::ShareDir::Install: 0.03
  File::Spec: 0
  File::Temp: 0
  File::pushd: 0
  Hash::Merge::Simple: 0
  JSON: 2
  List::AllUtils: 0
  List::MoreUtils: 0
  List::Util: 0
  Log::Dispatchouli: 1.102220
  Mixin::Linewise::Readers: 0.100
  Moose: 0.92
  Moose::Autobox: 0.10
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::LazyRequire: 0
  MooseX::Role::Parameterized: 0
  MooseX::SetOnce: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Perl: 0
  PPI: 0
  Params::Util: 0
  Path::Class: 0.22
  Path::Tiny: 0
  Perl::PrereqScanner: 1.016
  Perl::Version: 0
  Pod::Eventual: 0.091480
  Scalar::Util: 0
  Software::License: 0.101370
  Software::LicenseUtils: 0
  String::Formatter: 0.100680
  String::RewritePrefix: 0.005
  Sub::Exporter: 0
  Sub::Exporter::ForMethods: 0
  Sub::Exporter::Util: 0
  Term::Encoding: 0
  Term::ReadKey: 0
  Term::ReadLine: 0
  Term::UI: 0
  Test::Deep: 0
  Text::Glob: 0.08
  Text::Template: 0
  Try::Tiny: 0
  YAML::Tiny: 0
  autobox: 2.53
  autodie: 0
  namespace::autoclean: 0
  parent: 0
  perl: v5.8.5
  strict: 0
  version: 0
  warnings: 0
resources:
  Mailing_list: http://www.listbox.com/subscribe/?list_id=139292
  bugtracker: https://github.com/rjbs/Dist-Zilla/issues
  homepage: http://dzil.org/
  repository: https://github.com/rjbs/Dist-Zilla.git
version: 5.007
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Filter/Git::GatherDir'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Filter/CheckPrereqsIndexed'
      version: 0.010
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Filter/CheckExtraTests'
      version: 0.016
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 0
          check_all_prereqs: 0
          modules:
            - Dist::Zilla::PluginBundle::RJBS
          phase: build
          skip: []
      name: '@Filter/RJBS-Outdated'
      version: 0.015
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 1
          check_all_prereqs: 0
          modules: []
          phase: release
          skip: []
      name: '@Filter/CPAN-Outdated'
      version: 0.015
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/@Filter/PruneCruft'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/@Filter/ManifestSkip'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/@Filter/MetaYAML'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/@Filter/License'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/@Filter/Readme'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/@Filter/ExecDir'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/@Filter/ShareDir'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/@Filter/MakeMaker'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/@Filter/Manifest'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/@Filter/TestRelease'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/@Filter/ConfirmRelease'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/@Filter/UploadToCPAN'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: '@Filter/Test::ChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/ReportVersions::Tiny'
      version: 1.10
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Filter/TestMoreWithSubtests'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugin: '@RJBS'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: 4.005
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: 4.005
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@RJBS/SingleEncoding'
              version: 4.005
            -
              class: Pod::Weaver::Section::Name
              name: '@RJBS/Name'
              version: 4.005
            -
              class: Pod::Weaver::Section::Version
              name: '@RJBS/Version'
              version: 4.005
            -
              class: Pod::Weaver::Section::Region
              name: '@RJBS/Prelude'
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Synopsis'
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Description'
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Overview'
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Stability'
              version: 4.005
            -
              class: Pod::Weaver::Section::Collect
              name: Attributes
              version: 4.005
            -
              class: Pod::Weaver::Section::Collect
              name: Methods
              version: 4.005
            -
              class: Pod::Weaver::Section::Collect
              name: Functions
              version: 4.005
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@RJBS/Leftovers'
              version: 4.005
            -
              class: Pod::Weaver::Section::Region
              name: '@RJBS/postlude'
              version: 4.005
            -
              class: Pod::Weaver::Section::Authors
              name: '@RJBS/Authors'
              version: 4.005
            -
              class: Pod::Weaver::Section::Legal
              name: '@RJBS/Legal'
              version: 4.005
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '@RJBS/List'
              version: 4.005
      name: '@Filter/PodWeaver'
      version: 4.002
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Filter/GithubMeta'
      version: 0.42
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::ModuleShareDirs
      name: ModuleShareDirs
      version: 5.007
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 5.007
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 5.007
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 5.007
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: RuntimeRecommends
      version: 5.007
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 5.007
    -
      class: Dist::Zilla::Plugin::RemovePrereqs
      config:
        Dist::Zilla::Plugin::RemovePrereqs:
          modules_to_remove:
            - Config
            - Dist::Zilla::Tester::_Role
            - Some::Package::That::Does::Not::Exist::Due::To::A::Typo
      name: RemovePrereqs
      version: 5.007
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: CPANFile
      version: 5.007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.007
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.007
